src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewsRepository::class)]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $images = null;

    #[ORM\Column(length: 255)]
    private ?string $date = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }


    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;

use App\Entity\News;

class NewsController extends AbstractController
{
    public $doctrine;
 

    public function __construct(ManagerRegistry $doctrine)
    {
        $this->doctrine = $doctrine;
    }

    #[Route('/news', name: 'app_news')]
    public function index(ManagerRegistry $doctrine, PaginatorInterface $paginator, Request $request): Response
    {

        $sql = "SELECT bp FROM App\Entity\News bp ORDER BY bp.id DESC";
        $query = $doctrine->getManager()->createQuery($sql);

        $result = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            $request->query->getInt('limit', 10)/*limit per page*/
        );
    
        return $this->render('news/index.html.twig', [
            'controller_name' => 'NewsController',
            'news' => $result,
        ]);
    }


    public function save($data): Response
    {
        
        $entityManager = $this->doctrine->getManager();
    
        
        $news = $entityManager->getRepository(News::class)->findOneBy(['Title' => $data['title']]);
        if($news) {
            $news->setUpdatedAt(new \DateTimeImmutable());
            $news->setDescription($data['description']);
            $news->setImages($data['image']);
            $news->setDate($data['date']);
            $entityManager->flush();
        }else{
            $news = new News();
            $news->setTitle($data['title']);
            $news->setDescription($data['description']);
            $news->setImages($data['image']);
            $news->setDate($data['date']);
            $news->setCreatedAt(new \DateTimeImmutable());
            $news->setUpdatedAt(new \DateTimeImmutable());

            $entityManager->persist($news);
            $entityManager->flush();
        }
            
    

    
        return new Response('Saved new news with id '.$news->getId());
    }

    #[Route('/news/{id}', name: 'app_news_show')]
    public function getNews($id): Response
    {
        $news = $this->doctrine->getRepository(News::class)->find($id);
    
        if (!$news) {
            throw $this->createNotFoundException(
                'No news found for id '.$id
            );
        }
    
        return new Response('Check out this great news: '.$news->getTitle());
    }

    #[Route('/news/delete/{id}', name: 'app_news_delete')]
    public function delete($id): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $entityManager = $this->doctrine->getManager();
        $news = $entityManager->getRepository(News::class)->find($id);
    
        if (!$news) {
            throw $this->createNotFoundException(
                'No news found for id '.$id
            );
        }
    
        $entityManager->remove($news);
        $entityManager->flush();
    
        return new Response('News deleted successfully');
    }
}

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello NewsController!{% endblock %}


{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

{# boostrap table #}

    <div class="container">

    {# Page title #}

    <div class="row">
        <div class="col-md-12">
            <h1>News</h1>
        </div>
    </div>

    {# Table with pagination #}

    
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Description</th>
                            <th scope="col">Image</th>
                            <th scope="col">Date</th>
                            <th scope="col">Last updated</th>
                            <th scope="col">Actions</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for news in news %}
                        <tr>
                            <th scope="row">{{ news.id }}</th>
                            <td>{{ news.title }}</td>
                            <td>{{ news.description }}</td>
                            <td>
                                <img src="{{news.images}}" alt="image" width="100px" height="100px">
                            </td>
                            <td>{{ news.date }}</td>
                            <td>{{ news.updatedAt.format('d/m/Y') }}</td>
                            <td>
                            
                                {% if is_granted('ROLE_ADMIN') %}
                                    <a href="{{ path('app_news_delete', {'id': news.id}) }}" class="btn btn-danger">Delete</a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="navigation">
                    {{ knp_pagination_render(news) }}
                </div>
            </div>
        </div>


{% endblock %}